version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "npm"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    groups:
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    groups:
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    groups:
      all-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
