name: 'YAML Action'
description: 'Allows YAML Files to be edited'
author: 'Dylan Bono'

inputs:
  version:
    description: 'Version Number'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'