name: 'Flutter YAML Version'
description: 'Updates Flutter pubspec.yaml version'
author: 'Dylan Bono'

inputs:
  version:
    description: 'Version Number'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'