name: YAMl Action

on: 
  workflow_dispatch:

jobs: 
  yaml-action:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - uses: ./
      with:
        changes: |
          {
            "version": "2.0.1",
            "dependencies.flutter.sdk": "2.0.1"
          }
        commentOutDevDependencies: 'true'
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Testing Version Increase'
