name: YAMl Action

on: 
  workflow_dispatch:

jobs: 
  yaml-action:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - uses: ./
      with:
        version: 2.2.2 
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Testing Version Increase'
