name: YAMl Action

on: 
  workflow_dispatch:

jobs: 
  yaml-action:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - uses: ./
      with:
        changes: [
          ['dependencies.flutter.sdk', 'v2.1.0'],
          ['version', '2.1.0'],
        ]
        commentOutDevDependencies: 'true'
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Testing Version Increase'
